# Generated by Django 5.0.2 on 2024-05-09 13:33

import main.management.customselect.multiselect
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_dummy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='deliverystatus',
            field=main.management.customselect.multiselect.MyMultiSelectField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('pickedup', 'PickedUp'), ('statusCodeAdded', 'StatusCodeAdded'), ('attempted', 'Attempted Delivery')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilter',
            name='deliverystatus',
            field=main.management.customselect.multiselect.MyMultiSelectField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('pickedup', 'PickedUp'), ('statusCodeAdded', 'StatusCodeAdded'), ('attempted', 'Attempted Delivery')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='templatedfilters',
            name='deliverystatus',
            field=main.management.customselect.multiselect.MyMultiSelectField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('pickedup', 'PickedUp'), ('statusCodeAdded', 'StatusCodeAdded'), ('attempted', 'Attempted Delivery')], max_length=17, null=True),
        ),
    ]
