# Generated by Django 5.0.2 on 2024-05-11 21:10

import main.management.customselect.multiselect
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_deliverystatus_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='deliverystatus',
            field=main.management.customselect.multiselect.MyMultiSelectField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('pickedup', 'PickedUp'), ('statusCodeAdded', 'StatusCodeAdded'), ('attempted', 'Attempted Delivery')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilter',
            name='deliverystatus',
            field=main.management.customselect.multiselect.MyMultiSelectField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('pickedup', 'PickedUp'), ('statusCodeAdded', 'StatusCodeAdded'), ('attempted', 'Attempted Delivery')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='templatedfilters',
            name='deliverystatus',
            field=main.management.customselect.multiselect.MyMultiSelectField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('pickedup', 'PickedUp'), ('statusCodeAdded', 'StatusCodeAdded'), ('attempted', 'Attempted Delivery')], max_length=80, null=True),
        ),
    ]
