# Generated by Django 5.0.2 on 2024-05-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='reportorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
