# Generated by Django 5.0.2 on 2024-05-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_generatedreport_reportorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='liftgates',
            field=models.BooleanField(blank=True, null=True, verbose_name='Lift Gates'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='scac',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Scac'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='feinnumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='usdotnumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
