# Generated by Django 5.0.2 on 2024-05-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_carrier_canservice_alter_carrier_mexservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='sign_page_url',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='skip_signal',
        ),
    ]
